server.port=8080
spring.application.name=GestionSolicitudesAcademicas

spring.datasource.url=jdbc:postgresql://localhost:5432/gestionprueba
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=clave-supersecreta-para-la-gestion-de-solicitudes-academicas-uniquindio-2026-ingenieria-de-sistemas-y-computacion-pregrado
app.jwt.expiration-ms=900000

# IA con Groq
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
app.ia.habilitada=true

app.cors.allowed-origins=http://localhost:4200